# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# executable file names ########################################################

EXEC_NAME = el-montaje
EXEC_NAME_STATIC = el-montaje-static

EXEC_NAME_DEBUG = el-montaje-debug
EXEC_NAME_DEBUG_STATIC = el-montaje-debug-static

# extra flags ##################################################################

PROJECT_FLAGS =

# includes #####################################################################

include ../../libs/makefile-common.mk

# END ##########################################################################
